name: deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/prod/store-api
            ./stop.sh
            ./deploy.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}