name: deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup java environment
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package -DskipTests
      - name: copy jar file with scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/store-api-2.0.jar"
          target: "store-api"
      - name: run
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd store-api
            ./stop.sh
            nohup java -jar ./target/store-api-2.0.jar --jasypt.encryptor.password=${{ secrets.JASYPT_PASSWORD }} > log.log 2>&1 &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}